version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  automated-api-tests:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Apifox CLI
          command: npm install -g apifox-cli
      - run:
          name: Running Test Scenario
          command: apifox run http://192.168.10.208:5777/api/v1/projects/345197/api-test/ci-config/345120/detail?token=x0y5zt2ATvSPAwT-DtqoSd -r html,cli  -b
workflows:
  version: 2
  build:
    jobs:
      - automated-api-tests
