version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.04
jobs:
  automated-api-tests:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
      - run:
          name: Install Apifox CLI
          command: npm install -g apifox-cli
      - run:
          name: Running Test Scenario
          command: apifox run http://192.168.10.208:5777/api/v1/projects/345197/api-test/ci-config/345120/detail?token=x7KXd9ghBM1JvdVUaG67ZY -r html,cli  -b
workflows:
  version: 2
  build:
    jobs:
      - automated-api-tests